syntax = "proto3";

option csharp_namespace = "Core.API.Protos";

package menu;

service MenuService {
  rpc GetMenu (GetMenuRequest) returns (MenuResponse);
  rpc GetAllMenus (GetAllMenusRequest) returns (GetAllMenusResponse);
  rpc CreateMenu (CreateMenuRequest) returns (MenuResponse);
  rpc UpdateMenu (UpdateMenuRequest) returns (MenuResponse);
  rpc DeleteMenu (DeleteMenuRequest) returns (DeleteMenuResponse);
}

// Request messages
message GetMenuRequest {
  int32 id = 1;
}

message GetAllMenusRequest {
}

message CreateMenuRequest {
  string name = 1;
  string description = 2;
}

message UpdateMenuRequest {
  int32 id = 1;
  string name = 2;
  string description = 3;
}

message DeleteMenuRequest {
  int32 id = 1;
}

// Response messages
message MenuResponse {
  int32 id = 1;
  string name = 2;
  string description = 3;
}

message GetAllMenusResponse {
  repeated MenuResponse menus = 1;
}

message DeleteMenuResponse {
  bool success = 1;
}
